'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace TimbreFiscal
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TimbradoCFDISOAP", [Namespace]:="http://www.buzonfiscal.com/TimbradoCFDI/")>  _
    Partial Public Class TimbradoCFDI
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private timbradoCFDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Servicios.My.MySettings.Default.Servicios_TimbreFiscal_TimbradoCFDI
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event timbradoCFDCompleted As timbradoCFDCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.buzonfiscal.com/TimbradoCFDI/timbradoCFD", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function timbradoCFD(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.buzonfiscal.com/ns/xsd/bf/TimbradoCFD")> ByVal RequestTimbradoCFD As RequestTimbradoCFDType) As <System.Xml.Serialization.XmlElementAttribute("TimbreFiscalDigital", [Namespace]:="http://www.sat.gob.mx/TimbreFiscalDigital")> TimbreFiscalDigital
            Dim results() As Object = Me.Invoke("timbradoCFD", New Object() {RequestTimbradoCFD})
            Return CType(results(0),TimbreFiscalDigital)
        End Function
        
        '''<remarks/>
        Public Overloads Sub timbradoCFDAsync(ByVal RequestTimbradoCFD As RequestTimbradoCFDType)
            Me.timbradoCFDAsync(RequestTimbradoCFD, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub timbradoCFDAsync(ByVal RequestTimbradoCFD As RequestTimbradoCFDType, ByVal userState As Object)
            If (Me.timbradoCFDOperationCompleted Is Nothing) Then
                Me.timbradoCFDOperationCompleted = AddressOf Me.OntimbradoCFDOperationCompleted
            End If
            Me.InvokeAsync("timbradoCFD", New Object() {RequestTimbradoCFD}, Me.timbradoCFDOperationCompleted, userState)
        End Sub
        
        Private Sub OntimbradoCFDOperationCompleted(ByVal arg As Object)
            If (Not (Me.timbradoCFDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent timbradoCFDCompleted(Me, New timbradoCFDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.buzonfiscal.com/ns/xsd/bf/TimbradoCFD")>  _
    Partial Public Class RequestTimbradoCFDType
        
        Private documentoField As DocumentoType
        
        Private comprobanteField As Comprobante
        
        Private infoBasicaField As InfoBasicaType
        
        Private infoAdicionalField() As InfoAdicionalType
        
        Private refIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.buzonfiscal.com/ns/xsd/bf/RequestTimbraCFDI")>  _
        Public Property Documento() As DocumentoType
            Get
                Return Me.documentoField
            End Get
            Set
                Me.documentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
        Public Property Comprobante() As Comprobante
            Get
                Return Me.comprobanteField
            End Get
            Set
                Me.comprobanteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.buzonfiscal.com/ns/xsd/bf/RequestTimbraCFDI")>  _
        Public Property InfoBasica() As InfoBasicaType
            Get
                Return Me.infoBasicaField
            End Get
            Set
                Me.infoBasicaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("InfoAdicional")>  _
        Public Property InfoAdicional() As InfoAdicionalType()
            Get
                Return Me.infoAdicionalField
            End Get
            Set
                Me.infoAdicionalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Qualified, [Namespace]:="http://www.buzonfiscal.com/ns/xsd/bf/RequestTimbraCFDI")>  _
        Public Property RefID() As String
            Get
                Return Me.refIDField
            End Get
            Set
                Me.refIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.buzonfiscal.com/ns/xsd/bf/RequestTimbraCFDI")>  _
    Partial Public Class DocumentoType
        
        Private archivoField() As Byte
        
        Private nombreArchivoField As String
        
        Private tipoField As DocumentoTypeTipo
        
        Private versionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="base64Binary")>  _
        Public Property Archivo() As Byte()
            Get
                Return Me.archivoField
            End Get
            Set
                Me.archivoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property NombreArchivo() As String
            Get
                Return Me.nombreArchivoField
            End Get
            Set
                Me.nombreArchivoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Tipo() As DocumentoTypeTipo
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.buzonfiscal.com/ns/xsd/bf/RequestTimbraCFDI")>  _
    Public Enum DocumentoTypeTipo
        
        '''<remarks/>
        ZIP
        
        '''<remarks/>
        XML
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.buzonfiscal.com/ns/xsd/bf/RequestTimbraCFDI")>  _
    Partial Public Class InfoAdicionalType
        
        Private atributoField As String
        
        Private valorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Atributo() As String
            Get
                Return Me.atributoField
            End Get
            Set
                Me.atributoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Valor() As String
            Get
                Return Me.valorField
            End Get
            Set
                Me.valorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.buzonfiscal.com/ns/xsd/bf/RequestTimbraCFDI")>  _
    Partial Public Class InfoBasicaType
        
        Private rfcEmisorField As String
        
        Private rfcReceptorField As String
        
        Private serieField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property RfcEmisor() As String
            Get
                Return Me.rfcEmisorField
            End Get
            Set
                Me.rfcEmisorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property RfcReceptor() As String
            Get
                Return Me.rfcReceptorField
            End Get
            Set
                Me.rfcReceptorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Partial Public Class t_InformacionAduanera
        
        Private numeroField As String
        
        Private fechaField As Date
        
        Private aduanaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>  _
        Public Property fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property aduana() As String
            Get
                Return Me.aduanaField
            End Get
            Set
                Me.aduanaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Partial Public Class t_Ubicacion
        
        Private calleField As String
        
        Private noExteriorField As String
        
        Private noInteriorField As String
        
        Private coloniaField As String
        
        Private localidadField As String
        
        Private referenciaField As String
        
        Private municipioField As String
        
        Private estadoField As String
        
        Private paisField As String
        
        Private codigoPostalField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property calle() As String
            Get
                Return Me.calleField
            End Get
            Set
                Me.calleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property noExterior() As String
            Get
                Return Me.noExteriorField
            End Get
            Set
                Me.noExteriorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property noInterior() As String
            Get
                Return Me.noInteriorField
            End Get
            Set
                Me.noInteriorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property colonia() As String
            Get
                Return Me.coloniaField
            End Get
            Set
                Me.coloniaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property localidad() As String
            Get
                Return Me.localidadField
            End Get
            Set
                Me.localidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property referencia() As String
            Get
                Return Me.referenciaField
            End Get
            Set
                Me.referenciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property municipio() As String
            Get
                Return Me.municipioField
            End Get
            Set
                Me.municipioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property pais() As String
            Get
                Return Me.paisField
            End Get
            Set
                Me.paisField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property codigoPostal() As String
            Get
                Return Me.codigoPostalField
            End Get
            Set
                Me.codigoPostalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Partial Public Class t_UbicacionFiscal
        
        Private calleField As String
        
        Private noExteriorField As String
        
        Private noInteriorField As String
        
        Private coloniaField As String
        
        Private localidadField As String
        
        Private referenciaField As String
        
        Private municipioField As String
        
        Private estadoField As String
        
        Private paisField As String
        
        Private codigoPostalField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property calle() As String
            Get
                Return Me.calleField
            End Get
            Set
                Me.calleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property noExterior() As String
            Get
                Return Me.noExteriorField
            End Get
            Set
                Me.noExteriorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property noInterior() As String
            Get
                Return Me.noInteriorField
            End Get
            Set
                Me.noInteriorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property colonia() As String
            Get
                Return Me.coloniaField
            End Get
            Set
                Me.coloniaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property localidad() As String
            Get
                Return Me.localidadField
            End Get
            Set
                Me.localidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property referencia() As String
            Get
                Return Me.referenciaField
            End Get
            Set
                Me.referenciaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property municipio() As String
            Get
                Return Me.municipioField
            End Get
            Set
                Me.municipioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property pais() As String
            Get
                Return Me.paisField
            End Get
            Set
                Me.paisField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property codigoPostal() As String
            Get
                Return Me.codigoPostalField
            End Get
            Set
                Me.codigoPostalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Partial Public Class Comprobante
        
        Private emisorField As ComprobanteEmisor
        
        Private receptorField As ComprobanteReceptor
        
        Private conceptosField() As ComprobanteConcepto
        
        Private impuestosField As ComprobanteImpuestos
        
        Private complementoField As ComprobanteComplemento
        
        Private addendaField As ComprobanteAddenda
        
        Private versionField As String
        
        Private serieField As String
        
        Private folioField As String
        
        Private fechaField As Date
        
        Private selloField As String
        
        Private formaDePagoField As String
        
        Private noCertificadoField As String
        
        Private certificadoField As String
        
        Private condicionesDePagoField As String
        
        Private subTotalField As Decimal
        
        Private descuentoField As Decimal
        
        Private descuentoFieldSpecified As Boolean
        
        Private motivoDescuentoField As String
        
        Private tipoCambioField As String
        
        Private monedaField As String
        
        Private totalField As Decimal
        
        Private metodoDePagoField As String
        
        Private tipoDeComprobanteField As ComprobanteTipoDeComprobante
        
        Public Sub New()
            MyBase.New
            Me.versionField = "3.0"
        End Sub
        
        '''<remarks/>
        Public Property Emisor() As ComprobanteEmisor
            Get
                Return Me.emisorField
            End Get
            Set
                Me.emisorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Receptor() As ComprobanteReceptor
            Get
                Return Me.receptorField
            End Get
            Set
                Me.receptorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Concepto", IsNullable:=false)>  _
        Public Property Conceptos() As ComprobanteConcepto()
            Get
                Return Me.conceptosField
            End Get
            Set
                Me.conceptosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Impuestos() As ComprobanteImpuestos
            Get
                Return Me.impuestosField
            End Get
            Set
                Me.impuestosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Complemento() As ComprobanteComplemento
            Get
                Return Me.complementoField
            End Get
            Set
                Me.complementoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Addenda() As ComprobanteAddenda
            Get
                Return Me.addendaField
            End Get
            Set
                Me.addendaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property folio() As String
            Get
                Return Me.folioField
            End Get
            Set
                Me.folioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property sello() As String
            Get
                Return Me.selloField
            End Get
            Set
                Me.selloField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property formaDePago() As String
            Get
                Return Me.formaDePagoField
            End Get
            Set
                Me.formaDePagoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property noCertificado() As String
            Get
                Return Me.noCertificadoField
            End Get
            Set
                Me.noCertificadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property certificado() As String
            Get
                Return Me.certificadoField
            End Get
            Set
                Me.certificadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property condicionesDePago() As String
            Get
                Return Me.condicionesDePagoField
            End Get
            Set
                Me.condicionesDePagoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property subTotal() As Decimal
            Get
                Return Me.subTotalField
            End Get
            Set
                Me.subTotalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property descuento() As Decimal
            Get
                Return Me.descuentoField
            End Get
            Set
                Me.descuentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property descuentoSpecified() As Boolean
            Get
                Return Me.descuentoFieldSpecified
            End Get
            Set
                Me.descuentoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property motivoDescuento() As String
            Get
                Return Me.motivoDescuentoField
            End Get
            Set
                Me.motivoDescuentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TipoCambio() As String
            Get
                Return Me.tipoCambioField
            End Get
            Set
                Me.tipoCambioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Moneda() As String
            Get
                Return Me.monedaField
            End Get
            Set
                Me.monedaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property total() As Decimal
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property metodoDePago() As String
            Get
                Return Me.metodoDePagoField
            End Get
            Set
                Me.metodoDePagoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property tipoDeComprobante() As ComprobanteTipoDeComprobante
            Get
                Return Me.tipoDeComprobanteField
            End Get
            Set
                Me.tipoDeComprobanteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Partial Public Class ComprobanteEmisor
        
        Private domicilioFiscalField As t_UbicacionFiscal
        
        Private expedidoEnField As t_Ubicacion
        
        Private rfcField As String
        
        Private nombreField As String
        
        '''<remarks/>
        Public Property DomicilioFiscal() As t_UbicacionFiscal
            Get
                Return Me.domicilioFiscalField
            End Get
            Set
                Me.domicilioFiscalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExpedidoEn() As t_Ubicacion
            Get
                Return Me.expedidoEnField
            End Get
            Set
                Me.expedidoEnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property rfc() As String
            Get
                Return Me.rfcField
            End Get
            Set
                Me.rfcField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Partial Public Class ComprobanteReceptor
        
        Private domicilioField As t_Ubicacion
        
        Private rfcField As String
        
        Private nombreField As String
        
        '''<remarks/>
        Public Property Domicilio() As t_Ubicacion
            Get
                Return Me.domicilioField
            End Get
            Set
                Me.domicilioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property rfc() As String
            Get
                Return Me.rfcField
            End Get
            Set
                Me.rfcField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Partial Public Class ComprobanteConcepto
        
        Private itemsField() As Object
        
        Private cantidadField As Decimal
        
        Private unidadField As String
        
        Private noIdentificacionField As String
        
        Private descripcionField As String
        
        Private valorUnitarioField As Decimal
        
        Private importeField As Decimal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ComplementoConcepto", GetType(ComprobanteConceptoComplementoConcepto)),  _
         System.Xml.Serialization.XmlElementAttribute("CuentaPredial", GetType(ComprobanteConceptoCuentaPredial)),  _
         System.Xml.Serialization.XmlElementAttribute("InformacionAduanera", GetType(t_InformacionAduanera)),  _
         System.Xml.Serialization.XmlElementAttribute("Parte", GetType(ComprobanteConceptoParte))>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property unidad() As String
            Get
                Return Me.unidadField
            End Get
            Set
                Me.unidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property noIdentificacion() As String
            Get
                Return Me.noIdentificacionField
            End Get
            Set
                Me.noIdentificacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property valorUnitario() As Decimal
            Get
                Return Me.valorUnitarioField
            End Get
            Set
                Me.valorUnitarioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property importe() As Decimal
            Get
                Return Me.importeField
            End Get
            Set
                Me.importeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Partial Public Class ComprobanteConceptoComplementoConcepto
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Partial Public Class ComprobanteConceptoCuentaPredial
        
        Private numeroField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Partial Public Class ComprobanteConceptoParte
        
        Private informacionAduaneraField() As t_InformacionAduanera
        
        Private cantidadField As Decimal
        
        Private unidadField As String
        
        Private noIdentificacionField As String
        
        Private descripcionField As String
        
        Private valorUnitarioField As Decimal
        
        Private valorUnitarioFieldSpecified As Boolean
        
        Private importeField As Decimal
        
        Private importeFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("InformacionAduanera")>  _
        Public Property InformacionAduanera() As t_InformacionAduanera()
            Get
                Return Me.informacionAduaneraField
            End Get
            Set
                Me.informacionAduaneraField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property unidad() As String
            Get
                Return Me.unidadField
            End Get
            Set
                Me.unidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property noIdentificacion() As String
            Get
                Return Me.noIdentificacionField
            End Get
            Set
                Me.noIdentificacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property valorUnitario() As Decimal
            Get
                Return Me.valorUnitarioField
            End Get
            Set
                Me.valorUnitarioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property valorUnitarioSpecified() As Boolean
            Get
                Return Me.valorUnitarioFieldSpecified
            End Get
            Set
                Me.valorUnitarioFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property importe() As Decimal
            Get
                Return Me.importeField
            End Get
            Set
                Me.importeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property importeSpecified() As Boolean
            Get
                Return Me.importeFieldSpecified
            End Get
            Set
                Me.importeFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Partial Public Class ComprobanteImpuestos
        
        Private retencionesField() As ComprobanteImpuestosRetencion
        
        Private trasladosField() As ComprobanteImpuestosTraslado
        
        Private totalImpuestosRetenidosField As Decimal
        
        Private totalImpuestosRetenidosFieldSpecified As Boolean
        
        Private totalImpuestosTrasladadosField As Decimal
        
        Private totalImpuestosTrasladadosFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Retencion", IsNullable:=false)>  _
        Public Property Retenciones() As ComprobanteImpuestosRetencion()
            Get
                Return Me.retencionesField
            End Get
            Set
                Me.retencionesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Traslado", IsNullable:=false)>  _
        Public Property Traslados() As ComprobanteImpuestosTraslado()
            Get
                Return Me.trasladosField
            End Get
            Set
                Me.trasladosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property totalImpuestosRetenidos() As Decimal
            Get
                Return Me.totalImpuestosRetenidosField
            End Get
            Set
                Me.totalImpuestosRetenidosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property totalImpuestosRetenidosSpecified() As Boolean
            Get
                Return Me.totalImpuestosRetenidosFieldSpecified
            End Get
            Set
                Me.totalImpuestosRetenidosFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property totalImpuestosTrasladados() As Decimal
            Get
                Return Me.totalImpuestosTrasladadosField
            End Get
            Set
                Me.totalImpuestosTrasladadosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property totalImpuestosTrasladadosSpecified() As Boolean
            Get
                Return Me.totalImpuestosTrasladadosFieldSpecified
            End Get
            Set
                Me.totalImpuestosTrasladadosFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Partial Public Class ComprobanteImpuestosRetencion
        
        Private impuestoField As ComprobanteImpuestosRetencionImpuesto
        
        Private importeField As Decimal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property impuesto() As ComprobanteImpuestosRetencionImpuesto
            Get
                Return Me.impuestoField
            End Get
            Set
                Me.impuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property importe() As Decimal
            Get
                Return Me.importeField
            End Get
            Set
                Me.importeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Public Enum ComprobanteImpuestosRetencionImpuesto
        
        '''<remarks/>
        ISR
        
        '''<remarks/>
        IVA
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Partial Public Class ComprobanteImpuestosTraslado
        
        Private impuestoField As ComprobanteImpuestosTrasladoImpuesto
        
        Private tasaField As Decimal
        
        Private importeField As Decimal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property impuesto() As ComprobanteImpuestosTrasladoImpuesto
            Get
                Return Me.impuestoField
            End Get
            Set
                Me.impuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property tasa() As Decimal
            Get
                Return Me.tasaField
            End Get
            Set
                Me.tasaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property importe() As Decimal
            Get
                Return Me.importeField
            End Get
            Set
                Me.importeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Public Enum ComprobanteImpuestosTrasladoImpuesto
        
        '''<remarks/>
        IVA
        
        '''<remarks/>
        IEPS
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Partial Public Class ComprobanteComplemento
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Partial Public Class ComprobanteAddenda
        
        Private anyField() As System.Xml.XmlElement
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/cfd/3")>  _
    Public Enum ComprobanteTipoDeComprobante
        
        '''<remarks/>
        ingreso
        
        '''<remarks/>
        egreso
        
        '''<remarks/>
        traslado
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/TimbreFiscalDigital")>  _
    Partial Public Class TimbreFiscalDigital
        
        Private versionField As String
        
        Private uUIDField As String
        
        Private fechaTimbradoField As Date
        
        Private selloCFDField As String
        
        Private noCertificadoSATField As String
        
        Private selloSATField As String
        
        Public Sub New()
            MyBase.New
            Me.versionField = "1.0"
        End Sub
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property FechaTimbrado() As Date
            Get
                Return Me.fechaTimbradoField
            End Get
            Set
                Me.fechaTimbradoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property selloCFD() As String
            Get
                Return Me.selloCFDField
            End Get
            Set
                Me.selloCFDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property noCertificadoSAT() As String
            Get
                Return Me.noCertificadoSATField
            End Get
            Set
                Me.noCertificadoSATField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property selloSAT() As String
            Get
                Return Me.selloSATField
            End Get
            Set
                Me.selloSATField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub timbradoCFDCompletedEventHandler(ByVal sender As Object, ByVal e As timbradoCFDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class timbradoCFDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TimbreFiscalDigital
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TimbreFiscalDigital)
            End Get
        End Property
    End Class
End Namespace
